/**
 * Stage 01 driver: First Agent: the L0→L1 conceptual jump.
 *
 * L1 stage of the qa-minimal ladder.
 *
 * Generated by scripts/build-stages.mjs from modules/. Do not edit here.
 */
import { randomUUID } from 'node:crypto'
import { SessionId } from '@deepseek-ai/dsh-session'
import { createUserMessage } from '@deepseek-ai/dsh-llm'

export const inject = ['llm', 'agents']

const ROUTE = 'local-anthropic'

export function apply(ctx) {
  let done = false
  const kick = () => {
    if (done) return
    if (!ctx.llm.listProviders().some((p) => p.id === ROUTE)) return
    done = true
    void run(ctx)
  }
  ctx.on('llm/adapters-updated', kick)
  kick()
}

async function run(ctx) {
  await ctx.get('loader')?.await()

  const trace = process.env.QA_TRACE === '1'
  const question = process.env.QA_QUESTION
    || "用一句话说明插件化架构的好处"
  const model = process.env.QA_MODEL || 'deepseek-v4-flash'
  const resumeId = process.env.QA_RESUME

  if (trace) {
    ctx.on('session/event', (_session, event) => {
      console.log(`  [trace] ${event.type}`)
    })
  }

  let agent
  if (resumeId) {
    if (trace) console.log(`  [trace] resuming session ${resumeId}`)
    agent = (await ctx.agents.resume({
      resumeSessionId: SessionId(resumeId),
      agentOptions: { provider: ROUTE, model },
    })).agent
  } else {
    agent = (await ctx.agents.create({
      sessionId: SessionId(`qa-${randomUUID()}`),
      meta: { cwd: process.cwd() },
      agentOptions: { provider: ROUTE, model },
    })).agent
  }
  await agent.whenIdle()

  if (trace) console.log(`  [trace] agent ready · session ${agent.session.id}`)

  agent.followup(createUserMessage({
    content: [{ type: 'text', text: question }],
    source: { kind: 'user' },
  }))
  await agent.whenIdle()

  const sessions = ctx.get('sessions')
  if (sessions !== undefined) await sessions.flush(agent.session)

  const lastAssistant = [...agent.session.events]
    .reverse()
    .find((e) => e.type === 'assistant/message')
  const text = lastAssistant?.data?.message?.content
    ?.filter((b) => b.type === 'text')
    ?.map((b) => b.text)
    ?.join('') || '(no response)'

  console.log(text)
  console.log(`── session: ${agent.session.id} ──`)
  process.exit(0)
}
