import { validateComposition, normalizeName } from './validate.mjs'

// ── data loading ─────────────────────────────────────────────────────
// stages.json / catalog.json / graph.json are generated by
// scripts/build-web-data.mjs (machine facts, never hand-edited).
// curated.json is the hand-maintained layer: Chinese blurbs, roles,
// groups, per-level copy, and the abstract-seam list.

async function loadJson(path) {
  const res = await fetch(path)
  if (!res.ok) throw new Error(`${path}: HTTP ${res.status}`)
  return res.json()
}

const [stagesData, catalog, graph, curated] = await Promise.all([
  loadJson('./data/stages.json'),
  loadJson('./data/catalog.json'),
  loadJson('./data/graph.json'),
  loadJson('./data/curated.json'),
])

const groupOrder = curated.groupOrder
const abstractSeams = curated.abstractSeams ?? {}

function shortOf(fullName) { return normalizeName(fullName) }
function displayName(short) { return short === './driver.mjs' ? './driver.mjs' : short.replace(/^dsh-/, '') }

function pluginInfo(short) {
  const cur = curated.plugins[short] ?? {}
  const facts = catalog[short] ?? {}
  return {
    name: short,
    role: cur.role ?? 'core',
    group: cur.group ?? 'Other',
    blurb: cur.blurb ?? facts.description ?? '',
    note: cur.note ?? '',
    disabledOnWindows: Boolean(cur.disabledOnWindows),
    abstract: Boolean(abstractSeams[short]),
    inject: facts.inject ?? [],
    provides: facts.provides ?? [],
    version: facts.version ?? '',
  }
}

// The cordis.yml scanner cannot evaluate `disabled: !!js ...` expressions;
// entries marked disabledOnWindows in curated.json are only off on win32.
function entryDisabled(entry) {
  const info = pluginInfo(shortOf(entry.name))
  return info.disabledOnWindows ? false : entry.disabled
}

const stages = stagesData.map((s) => {
  const cur = curated.levels[String(s.level)] ?? {}
  return {
    level: s.level,
    title: cur.title ?? s.title,
    short: cur.short ?? '',
    story: cur.story ?? '',
    delta: cur.delta ?? '',
    defaultTask: cur.defaultTask ?? 'A',
    entries: s.entries,
    added: s.added.map(shortOf),
    removed: s.removed.map(shortOf),
  }
})

// ── behavior experiments (curated knowledge, not plugin data) ────────

const tasks = [
  { id:'A', label:'回答知识问题', detail:'只需要一次模型回答。' },
  { id:'B', label:'记住本轮信息', detail:'需要 Agent 会话而不只是裸调用。' },
  { id:'C', label:'重启后继续会话', detail:'需要持久化和 resume。' },
  { id:'D', label:'阅读项目文件', detail:'需要真实文件系统工具。' },
  { id:'E', label:'运行测试并改文件', detail:'需要文件工具和进程执行。' },
  { id:'F', label:'写工作区外文件', detail:'用来观察能力和权限的分离。' },
  { id:'G', label:'跟踪多步任务', detail:'需要 todo / plan / goal 状态。' },
  { id:'H', label:'委派子 Agent', detail:'需要 subagent Provider 和委派工具。' },
  { id:'I', label:'长任务运行', detail:'需要 workflow / ralph / compaction。' },
  { id:'J', label:'瞬时故障自愈 + 可测量', detail:'需要 retry 和 session stats。' }
]

function outcomeFor(taskId, level){
  switch(taskId){
    case 'A': return 'succeeds';
    case 'B': return level === 0 ? 'unsupported' : 'succeeds';
    case 'C': return level < 2 ? 'unsupported' : 'persists';
    case 'D': return level < 3 ? 'unsupported' : 'succeeds';
    case 'E': return level < 4 ? 'unsupported' : 'succeeds';
    case 'F': if(level < 4) return 'unsupported'; if(level === 4) return 'succeeds'; if(level === 5) return 'denied-by-sandbox'; return 'asks-approval';
    case 'G': return level < 7 ? 'unsupported' : 'succeeds';
    case 'H': return level < 8 ? 'unsupported' : 'succeeds';
    case 'I': return level < 9 ? 'unsupported' : 'succeeds';
    case 'J': return level < 10 ? 'unsupported' : 'succeeds';
  }
}

function outcomeExplain(taskId, level, outcome){
  if(outcome === 'unsupported'){
    const needs = {B:'Agent session', C:'session persistence', D:'Workspace FS', E:'Shell / Process', F:'Shell / Process', G:'Task state', H:'Subagent', I:'Workflow runtime', J:'Retry + stats'}[taskId];
    return `当前组合还没有 ${needs} 这组能力。任务不会进入执行阶段。`;
  }
  if(outcome === 'persists') return '会话事件已经有持久化后端。退出进程后，下一次可以用同一个 session id 恢复。';
  if(outcome === 'denied-by-sandbox') return '模型仍然有 bash 工具，但 Provider 被 workspace-write 约束。越界写入在执行边界被拒绝。';
  if(outcome === 'asks-approval') return 'Sandbox 先拒绝。模型可以带 justification 请求更宽权限，approval seam 接住这次升级。';
  const text = {A:'一次模型调用就够了。',B:'Session 把多轮消息放进同一条 Agent 历史。',D:'模型可以通过 read 工具拿到真实文件内容。',E:'模型既能改文件，也能启动真实程序验证结果。',G:'Todo / Plan / Goal 都有自己的持久状态。',H:'模型可以调用 subagent 或 subagent_fork，把任务交给子 Agent。',I:'长任务可以经过 workflow / ralph 循环，并在上下文压力升高时压缩历史。',J:'瞬时 Provider 错误进入 retry 路径，session projection 同时提供可测量统计。'}[taskId];
  return text || '当前组合已经具备这条能力路径。';
}

function traceFor(taskId, level){
  const outcome = outcomeFor(taskId, level);
  if(level === 0){
    if(outcome === 'unsupported') return [['event','ctx.llm.stream()'],['error',`task ${taskId}: capability is not mounted`],['result','process exit']];
    return [['event','ctx.llm.stream()'],['event','assistant chunks'],['result','answer → process exit']];
  }
  const lines = [['event','session created'],['event','turn/start'],['event','step/start'],['event','request/header']];
  if(outcome === 'unsupported') return [...lines,['error',`capability missing for task ${taskId}`],['event','step/end'],['result','turn/end']];
  if(taskId === 'C') lines.push(['event','session/flush'],['result','resumeSessionId → history restored']);
  if(taskId === 'D') lines.push(['event','tool/call · read'],['event','tool/result · file content']);
  if(taskId === 'E') lines.push(['event','tool/call · edit'],['event','tool/result · file changed'],['event','tool/call · bash'],['result','[exit code: 0]']);
  if(taskId === 'F'){
    lines.push(['event','tool/call · bash → ../outside.txt']);
    if(level === 4) lines.push(['result','write succeeds']);
    else if(level === 5) lines.push(['error','[sandbox: file access denied under workspace-write mode]']);
    else lines.push(['error','sandbox denies'],['event','retry · sandbox_permissions + justification'],['event','approval/asked'],['result','approval/decided → asks user']);
  }
  if(taskId === 'G') lines.push(['event','tool/call · todo_write'],['event','todo/write'],['event','goal/change'],['result','task state survives next step']);
  if(taskId === 'H') lines.push(['event','tool/call · subagent'],['event','subagent/start'],['event','child turn/start … turn/end'],['event','subagent/end'],['result','child final message → parent']);
  if(taskId === 'I') lines.push(['event','tool/call · ralph'],['event','workflow worker started'],['event','fresh child round × N'],['event','token pressure measured'],['result','compaction keeps task moving']);
  if(taskId === 'J') lines.push(['error','provider returns transient error'],['event','llm/retry'],['event','llm/retry-started'],['event','request succeeds'],['result','sessionStats updated']);
  if(!['C','D','E','F','G','H','I','J'].includes(taskId)) lines.push(['event','assistant/message']);
  lines.push(['event','step/end'],['result','turn/end']);
  return lines;
}

// ── shared state and helpers ─────────────────────────────────────────

const state = { view: 'build', stage: 0, task: 'A', onlyNew: false, traceTimer: null };

function escapeHtml(str){ return String(str).replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c])); }

function $(sel){ return document.querySelector(sel); }

// instance label for the two dsh-tool-subagent mounts (spawn / fork)
function instanceLabel(short, index, stage){
  if(short !== 'dsh-tool-subagent') return '';
  const occurrences = stage.entries.slice(0, index+1).filter(e => shortOf(e.name) === short).length;
  return occurrences === 1 ? 'spawn → subagent' : 'fork → subagent_fork';
}

// ── mode 1: guided assembly ──────────────────────────────────────────

const stageList = $('#stage-list');
const stageProgress = $('#stage-progress');
const stageKicker = $('#stage-kicker');
const stageTitle = $('#stage-title');
const stageStory = $('#stage-story');
const pluginCount = $('#plugin-count');
const deltaSummary = $('#delta-summary');
const deltaBricks = $('#delta-bricks');
const brickBoard = $('#brick-board');
const onlyNewToggle = $('#only-new-toggle');
const taskPicker = $('#task-picker');
const behaviorResult = $('#behavior-result');
const behaviorExplain = $('#behavior-explain');
const traceTerminal = $('#trace-terminal');
const traceStage = $('#trace-stage');
const playTrace = $('#play-trace');
const abSpotlight = $('#ab-spotlight');

function renderStageList(){
  stageList.innerHTML = stages.map(s => `
    <button class="stage-item ${s.level===state.stage?'active':''}" data-stage="${s.level}">
      <span class="stage-dot"></span>
      <span class="stage-row"><span class="stage-level">L${s.level}</span><span class="stage-count">${s.entries.length} blocks</span></span>
      <span class="stage-name">${escapeHtml(s.title)}</span>
      <span class="stage-one-liner">${escapeHtml(s.short)}</span>
    </button>`).join('');
  stageList.querySelectorAll('[data-stage]').forEach(btn => btn.addEventListener('click', () => selectStage(Number(btn.dataset.stage))));
}

function renderDelta(stage){
  deltaSummary.textContent = stage.delta;
  const add = stage.added.map(k => `<span class="mini-brick add">${escapeHtml(displayName(k))}</span>`);
  const remove = stage.removed.map(k => `<span class="mini-brick remove">${escapeHtml(displayName(k))}</span>`);
  deltaBricks.innerHTML = [...remove, ...add].join('') || '<span class="mini-brick">no delta</span>';
}

function renderBoard(stage){
  const addedSet = new Set(stage.added);
  const visible = stage.entries
    .map((entry, i) => ({ entry, i }))
    .filter(({ entry }) => !state.onlyNew || addedSet.has(shortOf(entry.name)) || shortOf(entry.name) === './driver.mjs');
  const groups = new Map();
  visible.forEach(({ entry, i }) => {
    const short = shortOf(entry.name);
    const info = pluginInfo(short);
    if(!groups.has(info.group)) groups.set(info.group, []);
    groups.get(info.group).push({ entry, i, info, short });
  });
  brickBoard.innerHTML = groupOrder.filter(g => groups.has(g)).map(group => {
    const bricks = groups.get(group).map(({ entry, i, info, short }) => {
      const isNew = addedSet.has(short);
      const inherited = !isNew && stage.level > 0;
      const disabled = entryDisabled(entry);
      const instance = instanceLabel(short, i, stage);
      return `<button class="brick ${isNew?'new':''} ${inherited?'inherited':''} ${disabled?'disabled':''}" data-plugin="${escapeHtml(short)}" data-role="${info.role}" title="${escapeHtml(short)} · 点击查看组件说明">
        ${escapeHtml(displayName(short))}${instance?`<span class="instance">${instance}</span>`:''}
      </button>`;
    }).join('');
    return `<section class="brick-group"><div class="group-label">${group}</div><div class="brick-row">${bricks}</div></section>`;
  }).join('');
  brickBoard.querySelectorAll('[data-plugin]').forEach(btn => btn.addEventListener('click', () => openPlugin(btn.dataset.plugin)));
}

function renderBehavior(){
  const outcome = outcomeFor(state.task, state.stage);
  behaviorResult.textContent = outcome;
  behaviorResult.className = `outcome ${outcome}`;
  behaviorExplain.textContent = outcomeExplain(state.task, state.stage, outcome);
  traceStage.textContent = `L${state.stage}`;
  renderTrace(false);
  renderSpotlight();
}

function renderSpotlight(){
  if(state.task !== 'F' || state.stage < 4 || state.stage > 6){
    abSpotlight.classList.add('hidden');
    abSpotlight.innerHTML = '';
    return;
  }
  abSpotlight.classList.remove('hidden');
  const rows = [4,5,6].map(l => {
    const out = outcomeFor('F',l);
    return `<div class="ab-row"><span class="ab-level">L${l}</span><span class="ab-action">同一条越界写入</span><span class="outcome ${out}">${out}</span></div>`;
  }).join('');
  abSpotlight.innerHTML = `<div class="ab-title">L4 → L5 → L6 单一变量实验</div>${rows}`;
}

function renderTrace(animated){
  if(state.traceTimer) clearInterval(state.traceTimer);
  const trace = traceFor(state.task, state.stage);
  traceTerminal.innerHTML = '';
  let i = 0;
  const pushLine = (kind, text, idx, animate) => {
    const div = document.createElement('div');
    div.className = `trace-line ${kind}`;
    if(!animate){ div.style.animation = 'none'; div.style.opacity = '1'; div.style.transform = 'none'; }
    div.innerHTML = `<span class="seq">${String(idx+1).padStart(2,'0')}</span>${escapeHtml(text)}`;
    traceTerminal.appendChild(div);
    traceTerminal.scrollTop = traceTerminal.scrollHeight;
  };
  if(animated){
    pushLine(...trace[0], 0, true);
    i = 1;
    state.traceTimer = setInterval(() => {
      if(i >= trace.length){ clearInterval(state.traceTimer); return; }
      pushLine(...trace[i], i, true);
      i++;
    }, 300);
  } else {
    trace.forEach(([kind, text], idx) => pushLine(kind, text, idx, false));
  }
}

function selectStage(level, { updateHash = true } = {}){
  stopLive();
  resetLiveView();
  updateLivePlaceholder();
  state.stage = level;
  state.task = stages[level].defaultTask;
  taskPicker.value = state.task;
  const stage = stages[level];
  stageProgress.textContent = `L${level} / L11`;
  stageKicker.textContent = `Level ${level}`;
  stageTitle.textContent = stage.title;
  stageStory.textContent = stage.story;
  pluginCount.textContent = stage.entries.length;
  renderStageList();
  renderDelta(stage);
  renderBoard(stage);
  renderBehavior();
  if(updateHash) setHash(`#L${level}`);
}

function renderTaskPicker(){
  taskPicker.innerHTML = tasks.map(t => `<option value="${t.id}">${t.id}. ${t.label}</option>`).join('');
  taskPicker.value = state.task;
}

// ── mode 2: behavior matrix ──────────────────────────────────────────

function renderMatrix(){
  const table = $('#behavior-matrix');
  const head = `<thead><tr><th>任务</th>${stages.map(s=>`<th>L${s.level}<br><small>${escapeHtml(s.title)}</small></th>`).join('')}</tr></thead>`;
  const body = `<tbody>${tasks.map(t => `<tr><th>${t.id}. ${t.label}</th>${stages.map(s => { const o=outcomeFor(t.id,s.level); return `<td class="matrix-cell" data-stage="${s.level}" data-task="${t.id}" data-outcome="${o}">${o}</td>`; }).join('')}</tr>`).join('')}</tbody>`;
  table.innerHTML = head + body;
  table.querySelectorAll('.matrix-cell').forEach(cell => cell.addEventListener('click', () => {
    setView('build', { updateHash: false });
    selectStage(Number(cell.dataset.stage));
    state.task = cell.dataset.task;
    taskPicker.value = state.task;
    renderBehavior();
  }));
}

// ── mode 3: free assembly ────────────────────────────────────────────

const free = { mounted: [], seeded: false, search: '' };
const catalogSearch = $('#catalog-search');
const catalogList = $('#catalog-list');
const catalogCount = $('#catalog-count');
const freeBoard = $('#free-board');
const freeCount = $('#free-count');
const freeVerdict = $('#free-verdict');
const freeIssues = $('#free-issues');
const freeServiceList = $('#free-service-list');

const catalogNames = [...Object.keys(catalog).sort(), './driver.mjs'];

function seedFreeFromLevel(level){
  const seen = new Set();
  free.mounted = [];
  for(const entry of stages[level].entries){
    const short = shortOf(entry.name);
    if(entryDisabled(entry) || seen.has(short)) continue;
    seen.add(short);
    free.mounted.push(short);
  }
  free.seeded = true;
}

function freeValidation(){
  return validateComposition(free.mounted, catalog, abstractSeams);
}

function renderCatalog(){
  const query = free.search.trim().toLowerCase();
  const mountedSet = new Set(free.mounted);
  const groups = new Map();
  catalogNames.forEach(short => {
    const info = pluginInfo(short);
    if(query && !short.toLowerCase().includes(query) && !info.blurb.toLowerCase().includes(query)) return;
    if(!groups.has(info.group)) groups.set(info.group, []);
    groups.get(info.group).push({ short, info });
  });
  let shown = 0;
  catalogList.innerHTML = groupOrder.filter(g => groups.has(g)).map(group => {
    const bricks = groups.get(group).map(({ short, info }) => {
      shown++;
      const mounted = mountedSet.has(short);
      return `<button class="brick catalog-brick ${mounted?'mounted':''}" data-catalog="${escapeHtml(short)}" data-role="${info.role}" title="${escapeHtml(short)} · 点击放上/拿下底盘">
        ${escapeHtml(displayName(short))}${info.abstract?'<span class="abstract-tag">抽象缝</span>':''}
        <span class="catalog-blurb">${escapeHtml(info.blurb)}</span>
        <span class="brick-info" data-info="${escapeHtml(short)}" title="查看组件说明">i</span>
      </button>`;
    }).join('');
    return `<section class="catalog-group"><div class="group-label">${group}</div>${bricks}</section>`;
  }).join('') || '<div class="board-empty">没有匹配的积木。</div>';
  catalogCount.textContent = `${shown} / ${catalogNames.length}`;
  catalogList.querySelectorAll('[data-catalog]').forEach(btn => btn.addEventListener('click', () => {
    toggleFree(btn.dataset.catalog);
  }));
  catalogList.querySelectorAll('[data-info]').forEach(el => el.addEventListener('click', (e) => {
    e.stopPropagation();
    openPlugin(el.dataset.info);
  }));
}

function toggleFree(short){
  const idx = free.mounted.indexOf(short);
  if(idx >= 0) free.mounted.splice(idx, 1);
  else free.mounted.push(short);
  renderFree();
}

function renderFreeBoard(v){
  const danglingByPlugin = new Map();
  v.dangling.forEach(d => {
    if(!danglingByPlugin.has(d.plugin)) danglingByPlugin.set(d.plugin, []);
    danglingByPlugin.get(d.plugin).push(d.service);
  });
  const conflictPlugins = new Set(v.conflicts.flatMap(c => c.plugins));
  const barePlugins = new Set(v.bareAbstract.map(b => b.plugin));

  freeCount.textContent = free.mounted.length ? `${free.mounted.length} 块积木 · 点一块拿下来` : '';
  if(!free.mounted.length){
    freeBoard.innerHTML = '<div class="board-empty">底盘是空的。从左边目录点一块积木放上来。</div>';
    return;
  }
  const groups = new Map();
  free.mounted.forEach(short => {
    const info = pluginInfo(short);
    if(!groups.has(info.group)) groups.set(info.group, []);
    groups.get(info.group).push({ short, info });
  });
  freeBoard.innerHTML = groupOrder.filter(g => groups.has(g)).map(group => {
    const bricks = groups.get(group).map(({ short, info }) => {
      const cls = [];
      let flag = '';
      if(conflictPlugins.has(short)){ cls.push('conflict'); flag = '服务冲突'; }
      if(barePlugins.has(short)){ cls.push('bare'); flag = '裸抽象缝'; }
      if(danglingByPlugin.has(short)){ cls.push('dangling'); flag = `缺 ${danglingByPlugin.get(short).map(s => `ctx.${s}`).join('、')}`; }
      return `<button class="brick ${cls.join(' ')}" data-remove="${escapeHtml(short)}" data-role="${info.role}" title="点击拿下 ${escapeHtml(short)}">
        ${escapeHtml(displayName(short))}${flag?`<span class="brick-flag">${escapeHtml(flag)}</span>`:''}
        <span class="brick-info" data-info="${escapeHtml(short)}" title="查看组件说明">i</span>
      </button>`;
    }).join('');
    return `<section class="brick-group"><div class="group-label">${group}</div><div class="brick-row">${bricks}</div></section>`;
  }).join('');
  freeBoard.querySelectorAll('[data-remove]').forEach(btn => btn.addEventListener('click', () => toggleFree(btn.dataset.remove)));
  freeBoard.querySelectorAll('[data-info]').forEach(el => el.addEventListener('click', (e) => {
    e.stopPropagation();
    openPlugin(el.dataset.info);
  }));
}

function renderFreeVerdict(v){
  if(!free.mounted.length){
    freeVerdict.className = 'free-verdict';
    freeVerdict.textContent = '底盘是空的。从目录里挑积木，或以一个 Level 的组合为起点。';
  } else if(v.ok){
    freeVerdict.className = 'free-verdict ok';
    freeVerdict.innerHTML = `<strong>可以启动。</strong>${free.mounted.length} 块积木，${v.services.length} 个 ctx.* 服务。没有悬空依赖、服务冲突或裸抽象缝。`;
  } else {
    const parts = [];
    if(v.dangling.length) parts.push(`${v.dangling.length} 个悬空依赖`);
    if(v.conflicts.length) parts.push(`${v.conflicts.length} 个服务冲突`);
    if(v.bareAbstract.length) parts.push(`${v.bareAbstract.length} 个裸抽象缝`);
    freeVerdict.className = 'free-verdict bad';
    freeVerdict.innerHTML = `<strong>还不能启动：</strong>${parts.join('、')}。`;
  }
}

function renderFreeIssues(v){
  const rows = [];
  v.dangling.forEach(d => {
    rows.push(`<div class="issue dangling"><span class="issue-kind">悬空依赖</span><code>${escapeHtml(d.plugin)}</code> 等待 <code>ctx.${d.service}</code>，但底盘上没有积木提供它。Consumer 没有 Provider 永远不会激活。</div>`);
  });
  v.conflicts.forEach(c => {
    const hasAbstract = c.plugins.some(p => abstractSeams[p]);
    const hint = hasAbstract ? '真实 stage 的做法：抽象缝以 disabled 挂载，只保留实现。' : '';
    rows.push(`<div class="issue conflict"><span class="issue-kind">服务冲突</span><code>ctx.${c.service}</code> 有两块实现：${c.plugins.map(p => `<code>${escapeHtml(p)}</code>`).join('、')}。一个上下文一个实现，留一块。${hint}</div>`);
  });
  v.bareAbstract.forEach(b => {
    rows.push(`<div class="issue bare"><span class="issue-kind">裸抽象缝</span><code>${escapeHtml(b.plugin)}</code> 只注册了 <code>ctx.${b.service}</code> 的接口。${escapeHtml(b.reason)}</div>`);
  });
  freeIssues.innerHTML = rows.join('');
}

function renderFreeServices(v){
  if(!v.services.length){
    freeServiceList.innerHTML = '<span class="service-empty">还没有任何 ctx.* 服务。</span>';
    return;
  }
  const conflictServices = new Set(v.conflicts.map(c => c.service));
  freeServiceList.innerHTML = v.services.map(s => {
    const providers = v.providersByService[s] ?? [];
    const cls = conflictServices.has(s) ? 'service-chip conflict' : 'service-chip';
    return `<span class="${cls}">ctx.${s} <span class="chip-provider">← ${providers.map(escapeHtml).join(' + ')}</span></span>`;
  }).join('');
}

function renderFree(){
  const v = freeValidation();
  renderCatalog();
  renderFreeBoard(v);
  renderFreeVerdict(v);
  renderFreeIssues(v);
  renderFreeServices(v);
}

// ── live run (only with scripts/web-server.mjs; static mode disables it) ──

const live = { source: null, available: false };
const liveNote = $('#live-note');
const liveQuestion = $('#live-question');
const liveRunBtn = $('#live-run');
const liveTerminal = $('#live-terminal');
const liveAnswer = $('#live-answer');

function liveTaskLabel(){
  const task = tasks.find(t => t.id === stages[state.stage].defaultTask);
  return task ? task.label : '';
}

function updateLivePlaceholder(){
  liveQuestion.placeholder = `例：${liveTaskLabel()}。也可以输入自己的问题`;
}

function resetLiveView(){
  liveTerminal.innerHTML = '';
  liveTerminal.classList.add('hidden');
  liveAnswer.classList.add('hidden');
  liveAnswer.innerHTML = '';
}

function stopLive(){
  if(live.source){ live.source.close(); live.source = null; }
  if(live.available){
    liveRunBtn.disabled = false;
    liveRunBtn.textContent = '真实运行';
  }
}

function pushLiveLine(kind, text){
  const div = document.createElement('div');
  div.className = `trace-line ${kind}`;
  div.style.animation = 'none';
  div.style.opacity = '1';
  div.style.transform = 'none';
  div.textContent = text;
  liveTerminal.appendChild(div);
  liveTerminal.scrollTop = liveTerminal.scrollHeight;
}

function startLive(){
  const question = liveQuestion.value.trim() || liveTaskLabel();
  if(!question) return;
  resetLiveView();
  liveTerminal.classList.remove('hidden');
  liveRunBtn.textContent = '停止';
  liveNote.textContent = `正在真实运行 L${state.stage}，这会调用模型 API。事件逐条来自子进程。`;
  let sessionId = null;
  let settled = false;
  const source = new EventSource(`/api/run?level=${state.stage}&question=${encodeURIComponent(question)}`);
  live.source = source;
  const endRun = () => {
    settled = true;
    stopLive();
  };
  source.addEventListener('trace', (e) => pushLiveLine('event', JSON.parse(e.data).type));
  source.addEventListener('log', (e) => pushLiveLine('log', JSON.parse(e.data).line));
  source.addEventListener('session', (e) => { sessionId = JSON.parse(e.data).id; });
  source.addEventListener('done', (e) => {
    const { answer, code } = JSON.parse(e.data);
    pushLiveLine('result', `进程退出 · exit code ${code ?? '?'}`);
    liveAnswer.classList.remove('hidden');
    liveAnswer.innerHTML =
      `<div class="live-answer-text">${answer ? escapeHtml(answer) : '（没有文本回答）'}</div>`
      + (sessionId ? `<div class="live-session">session: ${escapeHtml(sessionId)}</div>` : '');
    liveNote.textContent = '运行结束。上面的回答是模型真实输出。';
    endRun();
  });
  source.addEventListener('error', (e) => {
    if(e.data){ // server-sent error (e.g. timeout)
      pushLiveLine('error', JSON.parse(e.data).message);
    } else if(!settled){
      pushLiveLine('error', '连接中断或请求被拒绝（服务器同一时刻只跑一个任务）。');
    }
    liveNote.textContent = '运行中断。';
    endRun();
  });
}

liveRunBtn.addEventListener('click', () => {
  if(live.source){
    stopLive();
    pushLiveLine('result', '已停止。服务器侧子进程随之终止。');
    liveNote.textContent = '已手动停止。';
  } else {
    startLive();
  }
});

async function initLive(){
  let cfg = null;
  try {
    const res = await fetch('/api/config');
    if(res.ok) cfg = await res.json();
  } catch { /* static server: no API at all */ }
  live.available = Boolean(cfg?.hasKey);
  if(!live.available){
    liveNote.textContent = '实时运行在静态服务器模式下不可用。在仓库根目录配好 QA_BASE_URL 和 QA_API_KEY，然后用 node scripts/web-server.mjs 启动，这里就能用了。';
    return;
  }
  liveNote.textContent = '输入问题，服务器会在本机真实启动 run.mjs。';
  liveQuestion.disabled = false;
  liveRunBtn.disabled = false;
  updateLivePlaceholder();
}

// ── plugin detail modal (#plugin/<name>) ─────────────────────────────

const pluginModal = $('#plugin-modal');
const pmContent = $('#pm-content');
const pmClose = $('#pm-close');

const roleLabels = { core: '主干', provider: '后端', tool: '模型工具', policy: '策略', state: '状态', ops: '横切能力' };

function knownPlugin(short){
  return short === './driver.mjs' || short in catalog || short in curated.plugins;
}

function pmChip(short){
  const info = pluginInfo(short);
  return `<button class="pm-chip" data-plugin-link="${escapeHtml(short)}" data-role="${info.role}" title="查看 ${escapeHtml(short)}">${escapeHtml(short)}</button>`;
}

// Contiguous level ranges for the mount-history summary, e.g. "L3 – L11".
function levelRanges(levels){
  const ranges = [];
  let start = levels[0], prev = levels[0];
  for(let i = 1; i <= levels.length; i++){
    if(levels[i] === prev + 1){ prev = levels[i]; continue; }
    ranges.push(start === prev ? `L${start}` : `L${start} – L${prev}`);
    start = prev = levels[i];
  }
  return ranges.join('、');
}

function mountHistory(short){
  return stages.map(s => {
    const hits = s.entries.map((e, i) => ({ entry: e, i })).filter(({ entry }) => shortOf(entry.name) === short);
    return hits.length ? { level: s.level, title: s.title, hits } : null;
  }).filter(Boolean);
}

// Levels where the plugin was swapped out, and by whom (same-service add).
function replacements(short, provides){
  return stages.filter(s => s.removed.includes(short)).map(s => {
    const replacers = s.added.filter(a => a !== short && (catalog[a]?.provides ?? []).some(svc => provides.includes(svc)));
    return { level: s.level, replacers };
  });
}

function renderPluginModal(short){
  const info = pluginInfo(short);

  const meta = [
    `<span class="pm-tag role" data-role="${info.role}">${roleLabels[info.role] ?? info.role} · ${escapeHtml(info.group)}</span>`,
    info.version ? `<span class="pm-tag">v${escapeHtml(info.version)}</span>` : '',
    info.abstract ? '<span class="pm-tag abstract">抽象缝</span>' : '',
  ].join('');

  const notes = [];
  if(info.note) notes.push(info.note);
  if(info.disabledOnWindows) notes.push('cordis.yml 里这条的 disabled 是条件表达式，只在 Windows 上生效；在当前运行环境它正常工作。');

  const injectHtml = info.inject.length
    ? info.inject.map(s => {
        const providers = (graph.providersByService[s] ?? []).filter(p => p !== short);
        const side = providers.length
          ? providers.map(pmChip).join('')
          : '<span class="pm-none">目录里没有 Provider，挂载后会是悬空依赖</span>';
        return `<div class="pm-svc-row"><span class="pm-svc-name">ctx.${s}</span><span class="pm-arrow">←</span>${side}</div>`;
      }).join('')
    : '<span class="pm-none">不依赖其他 ctx.* 服务</span>';

  const consumersByService = new Map();
  (graph.edges ?? []).filter(e => e.to === short).forEach(e => {
    if(!consumersByService.has(e.service)) consumersByService.set(e.service, []);
    if(!consumersByService.get(e.service).includes(e.from)) consumersByService.get(e.service).push(e.from);
  });
  const providesHtml = info.provides.length
    ? info.provides.map(s => {
        const consumers = consumersByService.get(s) ?? [];
        const side = consumers.length
          ? consumers.map(pmChip).join('')
          : '<span class="pm-none">目录里没有 Consumer</span>';
        return `<div class="pm-svc-row"><span class="pm-svc-name">ctx.${s}</span><span class="pm-arrow">→</span>${side}</div>`;
      }).join('')
    : '<span class="pm-none">不提供 ctx.* 服务</span>';

  const history = mountHistory(short);
  const historyHtml = history.length
    ? `<p class="pm-mount-summary">挂载于 ${levelRanges(history.map(h => h.level))}（共 ${history.length} 级）。点一级跳到逐级拼装。</p>
       <div class="pm-levels">${history.map(h => {
         const flags = [];
         h.hits.forEach(({ entry, i }) => {
           const instance = instanceLabel(short, i, stages[h.level]);
           if(instance) flags.push(`实例：${instance}`);
           if(entryDisabled(entry)) flags.push('<span class="lc-flag disabled">disabled 挂载（仅展示）</span>');
           else if(entry.disabled && info.disabledOnWindows) flags.push('仅 win32 禁用');
           if(entry.configKeys?.length) flags.push(`config: ${entry.configKeys.join(', ')}`);
         });
         const flagHtml = flags.map(f => f.startsWith('<span') ? f : `<span class="lc-flag">${escapeHtml(f)}</span>`).join('');
         return `<button class="pm-level-chip" data-level="${h.level}" title="跳到逐级拼装 L${h.level}：${escapeHtml(h.title)}"><span class="lc-name">L${h.level}</span>${flagHtml}</button>`;
       }).join('')}</div>`
    : '<p class="pm-none">没有出现在任何 Level 的插件图里。</p>';

  const replaceRows = replacements(short, info.provides).map(r => {
    if(r.replacers.length) return `<div class="pm-replace-row">在 L${r.level} 被 ${r.replacers.map(pmChip).join(' ')} 替换</div>`;
    return `<div class="pm-replace-row">在 L${r.level} 从组合中移除</div>`;
  }).join('');

  pmContent.innerHTML = `
    <div class="pm-head">
      <div id="pm-name" class="pm-name">${escapeHtml(short)}</div>
      <div class="pm-meta">${meta}</div>
    </div>
    <p class="pm-blurb">${escapeHtml(info.blurb)}</p>
    ${notes.map(n => `<p class="pm-note">${escapeHtml(n)}</p>`).join('')}
    ${info.abstract ? `<div class="pm-seam"><strong>抽象缝</strong>${escapeHtml(abstractSeams[short])}</div>` : ''}
    <section class="pm-section">
      <h4>连接关系</h4>
      <div class="pm-conn">
        <div class="pm-conn-block"><strong>依赖 inject</strong>${injectHtml}</div>
        <div class="pm-conn-block"><strong>提供 provides</strong>${providesHtml}</div>
      </div>
    </section>
    <section class="pm-section">
      <h4>挂载历史</h4>
      ${historyHtml}
    </section>
    ${replaceRows ? `<section class="pm-section"><h4>替换关系</h4>${replaceRows}</section>` : ''}`;

  pmContent.querySelectorAll('[data-plugin-link]').forEach(el => el.addEventListener('click', () => {
    // Plain hash assignment (no suppress) so hashchange re-renders the modal
    // and each chip hop is its own history entry.
    location.hash = `#plugin/${el.dataset.pluginLink}`;
  }));
  pmContent.querySelectorAll('[data-level]').forEach(el => el.addEventListener('click', () => {
    closePlugin({ updateHash: false });
    setView('build', { updateHash: false });
    selectStage(Number(el.dataset.level));
  }));
}

function openPlugin(short, { fromHash = false } = {}){
  if(!knownPlugin(short)) { closePlugin({ updateHash: false }); return; }
  renderPluginModal(short);
  pluginModal.classList.remove('hidden');
  document.body.classList.add('modal-open');
  pmClose.focus();
  if(!fromHash) setHash(`#plugin/${short}`);
}

function closePlugin({ updateHash = true } = {}){
  if(pluginModal.classList.contains('hidden')) return;
  pluginModal.classList.add('hidden');
  document.body.classList.remove('modal-open');
  if(updateHash) setHash(viewHash());
}

pmClose.addEventListener('click', () => closePlugin());
pluginModal.addEventListener('click', (e) => { if(e.target === pluginModal) closePlugin(); });
document.addEventListener('keydown', (e) => { if(e.key === 'Escape') closePlugin(); });

// ── hash routing (#L5 / #compare / #free / #plugin/<name>) ───────────

let suppressHash = false;

function viewHash(){
  return state.view === 'build' ? `#L${state.stage}` : `#${state.view}`;
}

function setHash(h){
  if(location.hash === h) return;
  suppressHash = true;
  location.hash = h;
}

function parseHash(){
  const h = decodeURIComponent(location.hash.replace(/^#/, ''));
  if(h.startsWith('plugin/')) return { plugin: h.slice(7) };
  const m = h.match(/^L(\d+)$/i);
  if(m) return { view: 'build', stage: Number(m[1]) };
  if(h === 'compare' || h === 'free') return { view: h };
  return { view: 'build' };
}

function applyHash(){
  const r = parseHash();
  if(r.plugin){ openPlugin(r.plugin, { fromHash: true }); return; }
  closePlugin({ updateHash: false });
  if(r.view) setView(r.view, { updateHash: false });
  if(Number.isInteger(r.stage) && stages[r.stage]) selectStage(r.stage, { updateHash: false });
}

window.addEventListener('hashchange', () => {
  if(suppressHash){ suppressHash = false; return; }
  applyHash();
});

// ── view switching and wiring ────────────────────────────────────────

function setView(name, { updateHash = true } = {}){
  state.view = name;
  closePlugin({ updateHash: false });
  document.querySelectorAll('.view').forEach(v => v.classList.toggle('active', v.id === `${name}-view`));
  document.querySelectorAll('.mode-tab[data-view]').forEach(b => b.classList.toggle('active', b.dataset.view === name));
  if(name === 'free'){
    if(!free.seeded) seedFreeFromLevel(state.stage);
    renderFree();
  }
  if(updateHash) setHash(viewHash());
}

document.querySelectorAll('.mode-tab[data-view]').forEach(btn => btn.addEventListener('click', () => setView(btn.dataset.view)));
onlyNewToggle.addEventListener('change', () => { state.onlyNew = onlyNewToggle.checked; renderBoard(stages[state.stage]); });
taskPicker.addEventListener('change', () => { state.task = taskPicker.value; renderBehavior(); });
playTrace.addEventListener('click', () => renderTrace(true));
$('#free-from-level').addEventListener('click', () => { seedFreeFromLevel(state.stage); renderFree(); });
$('#free-clear').addEventListener('click', () => { free.mounted = []; free.seeded = true; renderFree(); });
catalogSearch.addEventListener('input', () => { free.search = catalogSearch.value; renderCatalog(); });

renderTaskPicker();
renderMatrix();
selectStage(0, { updateHash: false });
initLive();
applyHash();
